{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name $name | trunc 63 | trimSuffix "-" }}
  labels:
    app: {{ printf "%s-%s" $.Release.Name $name | trunc 63 | trimSuffix "-" }}
spec:
  type: ClusterIP
  selector:
    app: {{ printf "%s-%s" $.Release.Name $name | trunc 63 | trimSuffix "-" }}
  ports:
    - name: http
      port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.port }}
      protocol: TCP
{{- end }}
